project:
  type: website

website:
  title: "Julia Martin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - analysis.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

